### PR TITLE
Navigation cadets html fix

### PR DESCRIPTION
**Pull request by aestriex**

### CODE REVIEW

**Comment by aestriex** [comment]
@plun1331 Hi sorry to bug you but do you know why it keeps conflicting?

**Comment by plun1331** [comment]
> @plun1331 Hi sorry to bug you but do you know why it keeps conflicting?

It should give you instructions on how to resolve them

**Comment by aestriex** [comment]
> > @plun1331 Hi sorry to bug you but do you know why it keeps conflicting?
> 
> It should give you instructions on how to resolve them

This is all it shows for the `src/javascript/index.js` error
Screenshot_20221221_110432

**Comment by plun1331** [comment]
> > > @plun1331 Hi sorry to bug you but do you know why it keeps conflicting?
> > 
> > 
> > It should give you instructions on how to resolve them
> 
> This is all it shows for the `src/javascript/index.js` error Screenshot_20221221_110432

Top one is what you're trying to push, bottom one is what's already on master
Chose one and delete the other, as well as the dividers

**Comment by plun1331** [comment]
cloudflare is hot

**Comment by aestriex** [comment]
thanks for the help

**Comment by plun1331** [comment]
reasons why cloudflare is hot
image

**Pull request merged**
